/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jd_blockchain_crypto_jniutils_hash_JNISHA256Utils */

#ifndef _Included_com_jd_blockchain_crypto_jniutils_hash_JNISHA256Utils
#define _Included_com_jd_blockchain_crypto_jniutils_hash_JNISHA256Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_blockchain_crypto_jniutils_hash_JNISHA256Utils
 * Method:    hash
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jd_blockchain_crypto_jniutils_hash_JNISHA256Utils_hash
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
