/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jd_blockchain_crypto_jniutils_hash_JNIRIPEMD160Utils */

#ifndef _Included_com_jd_blockchain_crypto_jniutils_hash_JNIRIPEMD160Utils
#define _Included_com_jd_blockchain_crypto_jniutils_hash_JNIRIPEMD160Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_blockchain_crypto_jniutils_hash_JNIRIPEMD160Utils
 * Method:    hash
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jd_blockchain_crypto_jniutils_hash_JNIRIPEMD160Utils_hash
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
